[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#F0F9FF"
secondaryBackgroundColor = "#E0F2FE"
textColor = "#1F2937"